version: '3.6'

services:
  order_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
      - /app/node_modules
    ports:
      - 3333:3333
    command: /bin/sh -c "yarn dev:server"
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_PORT_DEV=5432
      - DB_HOST_DEV=db_order
    depends_on:
      - db_order
  db_order:
    image: postgres:13.2-alpine
    ports:
      - 2503:5432
    volumes:
      - ./src/db/scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
