version: '3.3'

services:
  order_service:
    env_file: .env
    container_name: order_service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        YARN_PARAMS: dev:server
    volumes:
      - '.:/backend/'
    ports:
      - 3333:3333