version: '3.3'

services:
  order_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
      - /app/node_modules
    ports:
      - 3333:3333
    command: /bin/sh -c "yarn && yarn dev:server"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://todoapp@postgres/todos
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: todoapp
  #     POSTGRES_DB: todos

# version: '2'

# services:
#   web:
#     build: .
#     command: npm run dev
#     volumes:
#       - .:/usr/app/
#       - /usr/app/node_modules
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres
#     environment:
#       DATABASE_URL: postgres://todoapp@postgres/todos
#   postgres:
#     image: postgres:9.6.2-alpine
#     environment:
#       POSTGRES_USER: todoapp
#       POSTGRES_DB: todos


# version: '3.6'
# services:
#   server:
#     build:
#       context: .
#       target: development
#     command: ["npm", "run", "debug:server"]
#     container_name: server
#     ports:
#       - '8100:8100'
#       - '9229:9229'
#     volumes:
#       - './server/src:/var/build/server/src:delegated'
#       - './shared/src:/var/build/shared/src:delegated'